_target_: browsergym.experiments.benchmark.Benchmark
backends:
- nudgingarena
env_args_list:
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task44ProductScarcityP5I3-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task34ProductSocialProofP5I2-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task38ProductSocialProofP5I6-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task18ProductScarcityP5I2-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task36ProductSocialProofP5I4-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task47ProductIncentivesP5I1-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task50ProductIncentivesP5I4-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task30ProductAuthorityP5I5-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task11ProductSocialProofP5I4-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task29ProductAuthorityP5I4-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task27ProductAuthorityP5I2-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task43ProductScarcityP5I2-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task3ProductAuthorityP5I3-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task17ProductScarcityP5I1-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task20ProductLossAversionP5I1-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task21ProductLossAversionP5I2-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task22ProductIncentivesP5I1-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task16ProductGoalFramingP5I3-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task9ProductSocialProofP5I2-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task41ProductGoalFramingP5I3-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task25ProductIncentivesP5I4-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task37ProductSocialProofP5I5-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task46ProductLossAversionP5I2-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task6ProductAuthorityP5I6-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task35ProductSocialProofP5I3-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task39ProductGoalFramingP5I1-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task7ProductAuthorityP5I7-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task1ProductAuthorityP5I1-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task31ProductAuthorityP5I6-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task14ProductGoalFramingP5I1-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task48ProductIncentivesP5I2-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task32ProductAuthorityP5I7-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task28ProductAuthorityP5I3-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task4ProductAuthorityP5I4-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task42ProductScarcityP5I1-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task5ProductAuthorityP5I5-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task19ProductScarcityP5I3-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task33ProductSocialProofP5I1-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task8ProductSocialProofP5I1-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task49ProductIncentivesP5I3-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task23ProductIncentivesP5I2-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task24ProductIncentivesP5I3-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task40ProductGoalFramingP5I2-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task26ProductAuthorityP5I1-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task15ProductGoalFramingP5I2-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task45ProductLossAversionP5I1-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task12ProductSocialProofP5I5-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task13ProductSocialProofP5I6-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task2ProductAuthorityP5I2-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
- headless: true
  max_steps: 6
  record_video: false
  slow_mo: null
  storage_state: null
  task_kwargs: null
  task_name: nudgingarena.Task10ProductSocialProofP5I3-v0
  task_seed: 0
  viewport: null
  wait_for_user_message: false
high_level_action_set_args:
  _target_: browsergym.experiments.benchmark.base.HighLevelActionSetArgs
  demo_mode: 'off'
  multiaction: false
  retry_with_force: false
  strict: false
  subsets:
  - webarena
is_multi_tab: true
name: nudgingarena_tiny
supports_parallel_seeds: false
task_metadata:
  _target_: pandas.DataFrame
  data:
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task44ProductScarcityP5I3-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task34ProductSocialProofP5I2-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task38ProductSocialProofP5I6-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task18ProductScarcityP5I2-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task36ProductSocialProofP5I4-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task47ProductIncentivesP5I1-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task50ProductIncentivesP5I4-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task30ProductAuthorityP5I5-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task11ProductSocialProofP5I4-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task29ProductAuthorityP5I4-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task27ProductAuthorityP5I2-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task43ProductScarcityP5I2-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task3ProductAuthorityP5I3-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task17ProductScarcityP5I1-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task20ProductLossAversionP5I1-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task21ProductLossAversionP5I2-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task22ProductIncentivesP5I1-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task16ProductGoalFramingP5I3-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task9ProductSocialProofP5I2-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task41ProductGoalFramingP5I3-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task25ProductIncentivesP5I4-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task37ProductSocialProofP5I5-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task46ProductLossAversionP5I2-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task6ProductAuthorityP5I6-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task35ProductSocialProofP5I3-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task39ProductGoalFramingP5I1-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task7ProductAuthorityP5I7-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task1ProductAuthorityP5I1-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task31ProductAuthorityP5I6-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task14ProductGoalFramingP5I1-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task48ProductIncentivesP5I2-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task32ProductAuthorityP5I7-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task28ProductAuthorityP5I3-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task4ProductAuthorityP5I4-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task42ProductScarcityP5I1-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task5ProductAuthorityP5I5-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task19ProductScarcityP5I3-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task33ProductSocialProofP5I1-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task8ProductSocialProofP5I1-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task49ProductIncentivesP5I3-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task23ProductIncentivesP5I2-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task24ProductIncentivesP5I3-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task40ProductGoalFramingP5I2-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task26ProductAuthorityP5I1-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task15ProductGoalFramingP5I2-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task45ProductLossAversionP5I1-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task12ProductSocialProofP5I5-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task13ProductSocialProofP5I6-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task2ProductAuthorityP5I2-v0
  - browsergym_split: train
    task_category: shopping
    task_name: nudgingarena.Task10ProductSocialProofP5I3-v0
