# @package _global_

defaults:
  - _self_
  - agent: gpt4o-mini
  - benchmark: nudgelab
  - task: shopping
  - override hydra/launcher: ray

experiment:
  n_jobs: 1
  parallel_backend: sequential
  n_relaunch: 1
  logging_level_stdout: WARNING
  root_dir: ${hydra:runtime.cwd}/${oc.env:AGENTLAB_EXP_ROOT}
  continue_from: null

study:
  host: https://web.media.mit.edu/~mcherep/files/nudgelab/
  output_dir: ${hydra:runtime.cwd}/study
  experiment_path: experiment-study
  n_workers: 4

# Environment vars
env:
  wa_shopping_url: ${oc.env:WA_SHOPPING,http://matlaber12.media.mit.edu:7770/}

# Hydra-Specific settings
hydra:
  launcher:
    ray:
      init:
        include_dashboard: true
        dashboard_port: 8265
      remote:
        num_cpus: 1
        num_gpus: 0
