# @package _global_

defaults:
  - _self_
  - agent: gpt4o-mini
  - benchmark: nudgelab
  - task: test/bestseller_tabs
  - override hydra/launcher: ray

experiment:
  root_dir: ${hydra:runtime.cwd}/${oc.env:AGENTLAB_EXP_ROOT}
  n_jobs: 1
  parallel_backend: sequential
  n_relaunch: 1
  logging_level_stdout: WARNING
  name: ???

# Environment vars
env:
  wa_shopping_url: ${oc.env:WA_SHOPPING,http://matlaber12.media.mit.edu:7770/}

# Hydra-Specific settings
hydra:
  run:
    dir: ${experiment.root_dir}/${experiment.name}
  sweep:
    subdir: ${experiment.root_dir}/sweeps/${hydra.job.num}
  job:
    chdir: true
  launcher:
    ray:
      init:
        include_dashboard: true
        dashboard_port: 8265
        job_config:
          _target_: ray.job_config.JobConfig
          runtime_env:
            working_dir: "."
      remote:
        num_cpus: 1
        num_gpus: 0
