# @package _global_

defaults:
  - _self_
  - agent: gpt4o-mini
  - benchmark: nudgelab
  - task: test/bestseller

experiment:
  root_dir: ${hydra:runtime.cwd}/${oc.env:AGENTLAB_EXP_ROOT}
  n_jobs: 1
  parallel_backend: sequential
  n_relaunch: 1
  logging_level_stdout: WARNING

# Environment vars
env:
  wa_shopping_url: ${oc.env:WA_SHOPPING,http://matlaber12.media.mit.edu:7770/}

# Hydra-Specific settings
hydra:
  run:
    dir: ${experiment.root_dir}
  sweep:
    dir: ${experiment.root_dir}
