# @package _global_

defaults:
  - _self_
  - agent: gpt-5-mini
  - benchmark: abxlab
  - task: shopping
  - override hydra/launcher: ray

experiment:
  n_jobs: 1
  parallel_backend: sequential
  n_relaunch: 1
  logging_level_stdout: WARNING
  root_dir: ${hydra:runtime.cwd}/${oc.env:AGENTLAB_EXP_ROOT}
  continue_from: null

study:
  host: https://web.media.mit.edu/~mcherep/files/abxlab/
  output_dir: ${hydra:runtime.cwd}/study
  experiment_path: experiment-regular
  products_csv: ${hydra:runtime.cwd}/tasks/products.csv
  seed: 42
  n_workers: 32

# Environment vars
env:
  abxlab_url: ${oc.env:WA_SHOPPING}

# Hydra-Specific settings
hydra:
  launcher:
    ray:
      init:
        include_dashboard: false
        dashboard_port: 8265
      remote:
        num_cpus: 1
        num_gpus: 0
