_target_: agentlab.agents.generic_agent.generic_agent.GenericAgentArgs

defaults:
  - flags: default
  - _self_

chat_model_args:
  _target_: agentlab.llm.chat_api.LiteLLMModelArgs
  model_name: bedrock/us.deepseek.r1-v1:0
  max_total_tokens: 128000
  max_input_tokens: 128000
  max_new_tokens: 32768
  vision_support: false
  temperature: 0.1
  additional_drop_params:
    - logprobs
