_target_: agentlab.agents.generic_agent.generic_agent.GenericAgentArgs

defaults:
  - flags: default
  - _self_

chat_model_args:
  _target_: agentlab.llm.chat_api.LiteLLMModelArgs
  model_name: gemini/gemini-2.5-flash-preview-04-17
  max_total_tokens: 1048576
  max_input_tokens: 1048576
  max_new_tokens: 65536
  vision_support: true
  temperature: 0.1
