_target_: agentlab.agents.generic_agent.generic_agent.GenericAgentArgs

defaults:
  - flags: default
  - _self_

chat_model_args:
  _target_: agentlab.llm.chat_api.LiteLLMModelArgs
  model_name: gemini/gemini-1.5-pro
  max_total_tokens: 2097152
  max_input_tokens: 2097152
  max_new_tokens: 8192
  vision_support: true
  temperature: 0.1
