_target_: agentlab.agents.generic_agent.generic_agent.GenericAgentArgs

defaults:
  - flags: default
  - _self_

chat_model_args:
  _target_: agentlab.llm.chat_api.LiteLLMModelArgs
  model_name: gpt-4.1-nano-2025-04-14
  max_total_tokens: 1047576
  max_input_tokens: 1047576
  max_new_tokens: 32768
  vision_support: true
  temperature: 0.1
