_target_: agentlab.agents.generic_agent.generic_agent.GenericAgentArgs

defaults:
  - flags: default
  - _self_

chat_model_args:
  _target_: agentlab.llm.chat_api.LiteLLMModelArgs
  model_name: gpt-3.5-turbo-0125
  max_total_tokens: 16385
  max_input_tokens: 16385
  max_new_tokens: 4096
  temperature: 0.1
  vision_support: false
  log_probs: false
