_target_: agentlab.agents.generic_agent.generic_agent.GenericAgentArgs

defaults:
  - flags: gpt4o_default
  - _self_

chat_model_args:
  _target_: agentlab.llm.chat_api.OpenAIModelArgs
  model_name: gpt-4o
  max_total_tokens: 128000
  max_input_tokens: 128000
  max_new_tokens: 4096
  temperature: 0.1
  vision_support: true
  log_probs: false
