_target_: agentlab.agents.generic_agent.generic_agent.GenericAgentArgs

defaults:
  - flags: default
  - _self_

chat_model_args:
  _target_: agentlab.llm.chat_api.LiteLLMModelArgs
  model_name: bedrock/us.meta.llama4-scout-17b-instruct-v1:0
  max_total_tokens: 3500000
  max_input_tokens: 3500000
  max_new_tokens: 8192
  vision_support: true
  temperature: 0.1
  additional_drop_params:
    - logprobs
