_target_: agentlab.agents.generic_agent.generic_agent.GenericAgentArgs

defaults:
  - flags: default
  - _self_

chat_model_args:
  _target_: agentlab.llm.chat_api.LiteLLMModelArgs
  model_name: o3-mini-2025-01-31
  max_total_tokens: 200000
  max_input_tokens: 200000
  max_new_tokens: 100000
  temperature: 0.1
  vision_support: false
  log_probs: false
  additional_drop_params:
    - temperature
    - max_tokens
    - logprobs
