_target_: agentlab.agents.dynamic_prompting.ActionFlags
action_set:
  _target_: browsergym.experiments.benchmark.base.HighLevelActionSetArgs
  subsets:
    - bid
  multiaction: false
long_description: false
individual_examples: true
